import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url)
    const categoryId = searchParams.get('categoryId')
    const dateFrom = searchParams.get('dateFrom')
    const dateTo = searchParams.get('dateTo')
    const page = parseInt(searchParams.get('page') || '1')
    const limit = parseInt(searchParams.get('limit') || '20')
    const skip = (page - 1) * limit

    const where: any = {}
    if (categoryId) where.categoryId = parseInt(categoryId)
    if (dateFrom || dateTo) {
      where.expenseDate = {}
      if (dateFrom) where.expenseDate.gte = new Date(dateFrom)
      if (dateTo) where.expenseDate.lte = new Date(dateTo)
    }

    const [expenses, total] = await Promise.all([
      prisma.expense.findMany({
        where,
        include: {
          category: true,
        },
        orderBy: { expenseDate: 'desc' },
        skip,
        take: limit,
      }),
      prisma.expense.count({ where }),
    ])

    return NextResponse.json({
      data: expenses,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    })
  } catch (err) {
    console.error('GET /api/expenses error:', err)
    return NextResponse.json({ error: 'Gagal mengambil data pengeluaran' }, { status: 500 })
  }
}

export async function POST(req: Request) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await req.json()
    const { expenseDate, categoryId, amount, description, relatedSaleId } = body

    if (!expenseDate || !categoryId || !amount) {
      return NextResponse.json(
        { error: 'expenseDate, categoryId, dan amount wajib diisi' },
        { status: 400 }
      )
    }

    if (amount <= 0) {
      return NextResponse.json({ error: 'Amount harus lebih dari 0' }, { status: 400 })
    }

    // Only manual expenses (not auto-generated)
    const expense = await prisma.expense.create({
      data: {
        expenseDate: new Date(expenseDate),
        categoryId: parseInt(categoryId),
        amount,
        description: description ?? null,
        relatedSaleId: relatedSaleId ? parseInt(relatedSaleId) : null,
        isAutoGenerated: false,
        createdById: user.id,
        createdByName: user.name,
      },
      include: { category: true },
    })

    await prisma.activityLog.create({
      data: {
        userId: user.id,
        username: user.username,
        userName: user.name,
        role: user.role,
        action: 'create_expense',
        entityType: 'Expense',
        entityId: expense.id,
        summary: `Membuat pengeluaran: ${expense.category.name} - Rp ${amount.toLocaleString('id-ID')}`,
      },
    })

    return NextResponse.json(expense, { status: 201 })
  } catch (err) {
    console.error('POST /api/expenses error:', err)
    return NextResponse.json({ error: 'Gagal membuat pengeluaran' }, { status: 500 })
  }
}
