import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getCurrentUser } from '@/lib/auth'
import { reverseMovements } from '@/lib/services/stock'

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params
    const order = await prisma.sale.findUnique({
      where: { id: parseInt(id) },
      include: {
        customer: true,
        items: {
          include: { product: true },
        },
      },
    })

    if (!order) {
      return NextResponse.json({ error: 'Pesanan tidak ditemukan' }, { status: 404 })
    }

    return NextResponse.json(order)
  } catch (err) {
    console.error('GET /api/orders/[id] error:', err)
    return NextResponse.json({ error: 'Gagal mengambil data pesanan' }, { status: 500 })
  }
}

export async function PUT(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { id } = await params
    const orderId = parseInt(id)
    const body = await req.json()
    const { status } = body

    const order = await prisma.sale.findUnique({
      where: { id: orderId },
      include: { items: true },
    })

    if (!order) {
      return NextResponse.json({ error: 'Pesanan tidak ditemukan' }, { status: 404 })
    }

    // Validate status transition
    const validTransitions: Record<string, string[]> = {
      confirmed: ['shipped', 'cancelled'],
      shipped: ['delivered'],
    }

    if (!validTransitions[order.status]?.includes(status)) {
      return NextResponse.json(
        { error: `Transisi status tidak valid: ${order.status} -> ${status}` },
        { status: 400 }
      )
    }

    // Only owner can cancel
    if (status === 'cancelled' && user.role !== 'owner') {
      return NextResponse.json(
        { error: 'Hanya owner yang dapat membatalkan pesanan' },
        { status: 403 }
      )
    }

    if (status === 'cancelled') {
      // Reverse stock movements
      await reverseMovements({
        refType: 'sale',
        refId: orderId,
        reason: `Pembatalan pesanan ${order.invoiceNumber}`,
        createdById: user.id,
        createdByName: user.name,
      })

      // Delete auto-generated expenses
      await prisma.expense.deleteMany({
        where: {
          relatedSaleId: orderId,
          isAutoGenerated: true,
        },
      })
    }

    const updateData: any = { status }
    if (status === 'shipped') {
      updateData.shippedAt = new Date()
    }

    const updatedOrder = await prisma.sale.update({
      where: { id: orderId },
      data: updateData,
      include: {
        customer: true,
        items: { include: { product: true } },
      },
    })

    await prisma.activityLog.create({
      data: {
        userId: user.id,
        username: user.username,
        userName: user.name,
        role: user.role,
        action: `update_order_${status}`,
        entityType: 'Sale',
        entityId: orderId,
        summary: `Update pesanan ${order.invoiceNumber}: ${order.status} -> ${status}`,
      },
    })

    return NextResponse.json(updatedOrder)
  } catch (err) {
    console.error('PUT /api/orders/[id] error:', err)
    return NextResponse.json({ error: 'Gagal memperbarui pesanan' }, { status: 500 })
  }
}
